### ISSUE TITLE
TensorFlow dependency

### ISSUE THREAD

**Issue by rogershijin** [Zeleni9/pytorch-wgan#13]
Please correct me if I'm wrong, but it looks like you're using TensorFlow only for TensorBoard.  If the same features you're using are available in [https://pytorch.org/docs/stable/tensorboard.html](url), it may be possible to remove the TF dependency.

**Comment by Zeleni9** [comment]
I will remove tensorflow dependency and use torchvision.utils.SummaryWriter only. Thank you.
