### ISSUE TITLE
How does optimizer work when there are 3 backwards(real, fake, penalty)?

### ISSUE THREAD

**Issue by wook3024** [Zeleni9/pytorch-wgan#14]
I thought I should write like 
"D_cost = D_fake - D_real + gradient_penalty
D_cost.backward()" 
but I don't know why you use backward like that.

https://github.com/Zeleni9/pytorch-wgan/blob/18ac0a8e08a895ec81f04c5248d2cb55f2485d91/models/wgan_gradient_penalty.py#L174-L193

**Comment by 394510288** [comment]
self.D.zero_grad()
                    
                    z = torch.randn(self.args.batch_size, 1, 96).to(self.args.device)
                    tree = [z]
                    
                    with torch.no_grad():
                        fake_point = self.G(tree)         
                        
                    D_real = self.D(point)
                    D_realm = D_real.mean()

                    D_fake = self.D(fake_point)
                    D_fakem = D_fake.mean()

                    gp_loss = self.GP(self.D, point.data, fake_point.data)
                    
                    d_loss = -D_realm + D_fakem
                    d_loss_gp = d_loss + gp_loss
                    d_loss_gp.backward()
                    self.optimizerD.step()
TreeGAN
