### ISSUE TITLE
Dimensionality

### ISSUE THREAD

**Issue by NUS-Tim** [Zeleni9/pytorch-wgan#24]
Hello, bro, may I know that for DCGAN, why the output dimension of the Generator = Cx32x32 while in the comment it's C. The same problem also exists in the Discriminator, the dimensionality of the input is Cx32x32 instead of Cx64x64 mentioned in the comment. Did you skip a Fractional-Strided Conv and a Conv?

**Comment by Zeleni9** [comment]
I have seen the comment, I think comment is just wrong since all the input images from mnist, fashion-mnist and cifar-10 are channelx32x32 so you can ignore 64x comment. I will change that to Cx32x32.
