### ISSUE TITLE
Why does it keep reporting this error?“AssertionError: Torch not compiled with CUDA enabled”

### ISSUE THREAD

**Issue by leelbc** [Zeleni9/pytorch-wgan#28]
Traceback (most recent call last):
  File "E:/_BACKUP/lbc/pytorch-wgan-master/main.py", line 45, in <module>
    main(args)
  File "E:/_BACKUP/lbc/pytorch-wgan-master/main.py", line 33, in main
    model.train(train_loader)
  File "E:\_BACKUP\lbc\pytorch-wgan-master\models\dcgan.py", line 226, in train
    z = Variable(torch.randn(self.batch_size, 100, 1, 1).cuda(self.cuda_index))
  File "E:\anaconda\envs\pytorch-wgan-master\lib\site-packages\torch\cuda\__init__.py", line 164, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Process finished with exit code 1

**Comment by leelbc** [comment]
I installed cuda10.2 and cudnn7.6.5 for this virtual environment

**Comment by Zeleni9** [comment]
Go on [Pytorch website](https://pytorch.org/get-started/locally/) pip install torch with CUDA 10.2 version and it should work.

**Comment by leelbc** [comment]
ok, Thanks for the reminder, I can already run it, but according to the prompt I am using gpu for training, but the computer's resource manager shows 100% cpu usage, I am still checking the problem

**Comment by Zeleni9** [comment]
Did u try running $ nvidia-smi   command ? Or check torch using this commands: [Check torch GPU](https://stackoverflow.com/questions/48152674/how-to-check-if-pytorch-is-using-the-gpu). If u have cuda 10.2 that version check on pytorch website and install or reinstall cuda.
