### ISSUE TITLE
Normalized weight initialization

### ISSUE THREAD

**Issue by vgunjal** [Zeleni9/pytorch-wgan#3]
I noticed that in the implementation of WGAN with gradient penalty, the weights are not initialized from a normal distribution as is detailed here - https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html#weight-initialization

The same initialization is also done in the original WGAN implementation - https://github.com/martinarjovsky/WassersteinGAN/blob/f7a01e82007ea408647c451b9e1c8f1932a3db67/main.py#L108

May I know if this was done on purpose? Or was it just an unfortunate omission?

**Comment by Zeleni9** [comment]
It was not done on purpose, because it was not the main goal of the project. The goal was to assess the stability of the training with different datasets. There could be an improvement in adding it, but it would be minor.
