### ISSUE TITLE
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 2: out of memory

### ISSUE THREAD

**Issue by sumorday** [Zeleni9/pytorch-wgan#36]
2022-04-13 16:47:09.310913: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 2: out of memory

how to run the code in os terminal?

python main.py --model WGAN-GP \
               --is_train True \
               --download True \
               --dataroot datasets/cifar \
               --dataset cifar \
               --generator_iters 40000 \
               --cuda True \
               --batch_size 64
I tried many times. thanks in advance

**Comment by Zeleni9** [comment]
Try to resolve the problem using solution from Stackoverflow - [Solution](https://stackoverflow.com/questions/66371130/cuda-initialization-unexpected-error-from-cudagetdevicecount)
