### ISSUE TITLE
about walking in the latent space

### ISSUE THREAD

**Issue by luzhixing12345** [Zeleni9/pytorch-wgan#38]
https://github.com/Zeleni9/pytorch-wgan/blob/d5b9b4db573f2efbfa56e115d46b28d1f0465312/models/wgan_gradient_penalty.py#L384

Hello, great job that helps me a lot.
I wonder why did you use `alpha+=alpha ` in all models to increase alpha, why double alpha each time instead of using linear increasing?

**Comment by Zeleni9** [comment]
Because to move in latent space I used [0,1.0] scale to move and start with smallest part 1/10 then move to 10/10 since the number int = 10.
