### ISSUE TITLE
Mismatch in Shape while running WGAN-GP

### ISSUE THREAD

**Issue by AlexFxw** [Zeleni9/pytorch-wgan#5]
```
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).
```
I'm trying to fix the bug.

**Comment by Zeleni9** [comment]
Thank you for changes, it works on pytorch version stated in the README. I would probably update repo with latest pytorch version soon.
