### ISSUE TITLE
loss caculation in discriminator

### ISSUE THREAD

**Issue by xiaohongniua** [Zeleni9/pytorch-wgan#9]
why mone=-1 was passed to backward in fake_loss while one=1 passed  to backward in real_loss? for maximize(fake_loss) and minimize(real_loss)?

**Comment by stillstream** [comment]
I have the same question

**Comment by Zeleni9** [comment]
Better explanation lies in the r[eddit thread about the WGAN ](https://www.reddit.com/r/MachineLearning/comments/5qxoaz/r_170107875_wasserstein_gan/):

My implementation trick with AbsCriterion is just meant as a way of implementing constant gradients in Torch. By setting the target to be output +- 1, we guarantee that the gradient will be +- 1.

My initial reason for using +- 1 gradients was pretty much that the comments here say to. However, I was able to muster some intuition for it. If you look at Eq. 3 in the paper, you will notice that the maximum is reached when f_w(x) yields high values for real examples and low values for generated examples. This is exactly what we are working towards by pushing the critic up and down with +-1 gradients.
